### ISSUE TITLE
Excessive RPC clients created on connect & page load

### ISSUE THREAD

**Issue by dgabriele** [strangelove-ventures/wadesta#103]
## Describe the bug

Whenever you connect a wallet (e.g. via Keplr), Graz is clearly creating an unnecessary number of RPC clients internally, probably via `CosmWasmClient.connect`. If you look at network activity in the browser, you'll notice at least 4 concurrent requests to the RPC provider, targeting its "status" endpoint, which is what the `CosmWasmClient.connect` method automatically does each time it is called. This is not good. Depending on the RPC provider, this can trigger an HTTP 429 rate limit error. Instead, you guys really ought to manage a singleton client and make use of the batch RPC client available in cosmjs.

...

## To Reproduce

1. Open dev console in browser.
2. Navigate to your demo app.
3. Open "Network Activity" tab
4. Connect wallet via Keplr.
5. Notice the exessive XHR requests sent to the RPC's "status" method.

## Expected behavior
There should be only *one* request to the "status" method globally.

> A clear and concise description of what you expected to happen.

...

## Screenshots

![image](https://github.com/strangelove-ventures/graz/assets/215948/596947c0-fafe-457f-bc72-c92d1c96991e)

**Comment by codingki** [comment]
@dgabriele Yes we are aware of this, it will be solved in 0.1.x version. Read more https://github.com/strangelove-ventures/graz/discussions/102

**Comment by dgabriele** [comment]
Thanks! Sorry if I came across a bit curt. Been having a frustrating couple weeks. Head's exploding
