### ISSUE TITLE
Mobile Keplr & Leap workflows broken on Android

### ISSUE THREAD

**Issue by dgabriele** [strangelove-ventures/wadesta#104]
## Describe the bug
Upon duplicating the code in the example project, graz does not auto-open the Keplr or Leap mobile app as expected, via WalletConnect, upon calling `SigningCosmWasmClient.execute`. 

In the case of Keplr, the Chrome Android browser does not toggle into the mobile Keplr app. I and others who have tested must manually toggle into Keplr to approve the pending transaction.

When selecting Leap + WalletConnect on Android, the web app just opens up Leap in the Google Play store instead of going into the actual Leap app to approve the connection.

I can see that the mobile browser performs what looks like 2 requests in the background, as the loading bar seems to activate, but the app just stays on the current page while the Keplr app fails to launch.

## To Reproduce

We're running a Next.js v12 app. Nothing special. To reproduce, just do the boilerplate graz setup and try executing a contract via Keplr+WalletConnect or Leap.

**Comment by codingki** [comment]
@dgabriele Just to make sure, do you have keplr mobile installed on your android?

**Comment by dgabriele** [comment]
Of course! :) 

I've been developing and testing on Juno for the last 1.5 years or so. I'm not alone in this experience either. It's not just graz. I've tried cosmoskit as well as my own solutions. Seems to be something wonky with WalletConnect and/or Keplr mobile.

**Comment by codingki** [comment]
Before we release this, We were testing it and it works on android and ios. Yeah I can confirm, it's not always 100% works WalletConnect a bit wonky in mobile. 
I'll keep this issue opened, I'll investigate this more.

**Comment by dgabriele** [comment]
Thanks! Really appreciate it. I'm trying to get to the bottom of it as well and will let you know what I find, if anything. It's crazy how bad Keplr is at supporting their own software... really disappointing.

**Comment by codingki** [comment]
Can you try upgrading to `0.0.49` and see if you still experiencing this issue @dgabriele?
