### ISSUE TITLE
State reloads when Keplr TX window pops up

### ISSUE THREAD

**Issue by Callum-A** [strangelove-ventures/wadesta#11]
The Keplr TX window (to approve or deny) of course opens a new window, this forces a state refresh and often leads to local state being overriden. It feels like this refresh is too oppressive when compared with other setups.

To reproduce:

- Load some state from chain. (In my case it was some smart contract data)
- Allow the user to edit it locally.
- Attempt to sign a TX (in my case it was saving said changes to chain via executing a contract route)
- The page will force a reload and local changes will be lost.

**Comment by grikomsn** [comment]
Can you provide an example repo? Might help to give more context about the issue.

My educated guess is either one of the query hooks refetches on mount[^1] or due to reconnection on `focus` or `keplr_keystorechange` events[^2].

[^1]: https://react-query-v3.tanstack.com/guides/window-focus-refetching
[^2]: https://github.com/strangelove-ventures/graz/blob/50e136b53143e9e4f6d83cb6cff059d86150e2cd/packages/graz/src/provider/subscription.tsx#L8-L22

**Comment by Callum-A** [comment]
This sounds like it would be the cause, do any of these reconnections change SigningCosmWasmClient or CosmWasmClient in anyway, as that would cause my useEffect deps to refresh.

**Comment by codingki** [comment]
Currently we get signer and client inside `useConnect`'s `connect` but it make sense we put it there.
I'm thinking we can separate these `useConnect`, `useSigner` and `useClient`
`useConnect` will only responsible with `keplr.enable` and getting `Key`

What do y'all think?

**Comment by codingki** [comment]
> This sounds like it would be the cause, do any of these reconnections change SigningCosmWasmClient or CosmWasmClient in anyway, as that would cause my useEffect deps to refresh.

It can be, because we call `connect()` every focus, and connect responsible to setState signer and clients https://github.com/strangelove-ventures/graz/blob/50e136b53143e9e4f6d83cb6cff059d86150e2cd/packages/graz/src/actions/account.ts#L29-L34

**Comment by codingki** [comment]
What do you put in the useEffect deps @Callum-A ?

**Comment by Callum-A** [comment]
The signingClient, is there a way it could only be updated if the account or chain changes?

**Comment by codingki** [comment]
We might going to remove the `focus` listener, It was a hack to get around the `keplr_keystorechange` was not working.
on v.0.0.7

**Comment by Callum-A** [comment]
> We might going to remove the `focus` listener, It was a hack to get around the `keplr_keystorechange` was not working. on v.0.0.7

I feel like this is the best solution

**Comment by codingki** [comment]
Fixed on https://github.com/strangelove-ventures/graz/commit/3ba8526358aba290269b37b4462ce38060d6b361, We already shipped `v.0.0.7` try to bump your `graz` version @Callum-A.
