### ISSUE TITLE
Cannot use leap cosmos metamask snap with testnets 

### ISSUE THREAD

**Issue by antho31** [strangelove-ventures/wadesta#117]
## Describe the bug

I succeed to use Leap Metamask snap with Cosmos Hub, Osmosis and other mainnet chains, but if I use one from a testnet, it did not work. I got "Invalid chainId error". 

## To Reproduce

1. [Use the Next example, and look at `_app.tsx` file](https://github.com/graz-sh/graz/blob/dev/example/next/pages/_app.tsx)
2. Let's assume `ChainInfo` is generated (`yarn graz generate -g`), import  `testnetChains`  from `"graz/chains"`
3. Provide `grazOptions={{ defaultChain: testnetChains.okp4testnet }}` in `GrazProvider` 
4. Run, open it in a browser, connect with Leap Metamask Snap
5. See error in Console Tab from the Dev tools

## Expected behavior

Expect Connection with Leap Metamask Snap to work with any testnet as well as with any mainnet. 

## Additional context

Try with any available network from `testnetChains`

**Comment by antho31** [comment]
FYI @amimart @ccamel

**Comment by codingki** [comment]
Hey @antho31 for testnet chains, you can't use `useConnect` you need to use [`useSuggestChainAndConnect`](https://graz.sh/docs/hooks/useSuggestChainAndConnect). check this https://github.com/graz-sh/graz/blob/dev/example/next/ui/chain-switcher.tsx

as for connecting testnet chains with leap metamask snap I did repro it, yeah it having issues using suggesting a testnet chain. For now for connect/suggest testnet chains don't use metamask snap leap until further notice.

We already raised this issue to leap team. will inform you if we have any update

**Comment by codingki** [comment]
@antho31 We already raised this issue to leap team. will inform you if we have any update

**Comment by antho31** [comment]
Thanks for your response, clear to me. Let me know when it will be available for testnets :)

**Comment by codingki** [comment]
Re: Metamask snap. We found the issue, will be fixed in `0.0.50` @antho31 thanks for the report. will keep this issue open until it released

**Comment by codingki** [comment]
@antho31 This issue is fixed in v0.0.50. Now you can suggest chain with MetaMask Snap Leap. Also you can use graz without MetaMask Flask 

https://github.com/graz-sh/graz/releases/tag/v0.0.50

**Comment by antho31** [comment]
Thank you for this effectiveness, well done, I'm able to connect to a testnet with Metamask!
