### ISSUE TITLE
Add support for signArbitrary

### ISSUE THREAD

**Issue by jhernandezb** [strangelove-ventures/wadesta#128]
## Is your feature request related to a problem? Please describe.

Add support for `signArbitrary` method that follows cosmos [ADR36](https://github.com/cosmos/cosmos-sdk/blob/main/docs/architecture/adr-036-arbitrary-signature.md)
## Describe the solution you'd like

A method to sign arbitrary data similar to cosmos-kit
https://github.com/cosmology-tech/cosmos-kit/blob/162e087be99508a4bd560f7ffdd45d11a51a4801/wallets/keplr-extension/src/extension/client.ts#L148
## Describe alternatives you've considered
I've tried to get access to the client/signer directly but can't find a way to get access to similar method.

**Comment by codingki** [comment]
Not all wallet supports `signArbitrary`, I'll add it the wallet type as a conditional function in next release

**Comment by codingki** [comment]
usage will be 
```ts
const { walletType } = useActiveWalletType();
const wallet = getWallet(walletType);
wallet.signArbitrary()
```

**Comment by codingki** [comment]
Released v.0.1.3 https://github.com/graz-sh/graz/releases/tag/v.0.1.3
