### ISSUE TITLE
Update dependencies with the latest

### ISSUE THREAD

**Issue by btc8436954** [strangelove-ventures/wadesta#136]
## Is your feature request related to a problem? Please describe.

> `react-query` version doesn't match. I have `react-query@^5.18.1` in my nextjs project, but you are using `^4.35.0"`. I am using nextjs latest version with app router, fyi

<img width="1024" alt="image" src="https://github.com/graz-sh/graz/assets/49041460/e2b8ea36-8fd8-4887-9769-9769735ef685">

...

## Describe the solution you'd like

> Upgrade versions for dependencies

...

## Describe alternatives you've considered

> I will not use `graz`, since it's breaking.

...

## Additional context

> Screenshot attached above

...

**Comment by btc8436954** [comment]
Sorry, this bug is not related to the version mismatch. I was able to fix it by rendering the Wallet component on the client side only. Thank you.

**Comment by codingki** [comment]
Glad that you found the fix
