### ISSUE TITLE
Error: There is no chain info for RockChain

### ISSUE THREAD

**Issue by btc8436954** [strangelove-ventures/wadesta#143]
## Describe the bug

I get error when connecting the Keplr wallet on my dapp. Error:

```
Wallet.tsx:61 connect  Error: There is no chain info for RockChain
```

```typescript
const { connect } = useConnect();

connect({
    walletType: WalletType.KEPLR,
    chainId: PUBLIC_ENVIRONMENT.NEXT_PUBLIC_CHAIN_ID,
  });

```

## To Reproduce

1. I am on my local test app
2. Click on 'Connect' button
3. See error

## Expected behavior

It should connect the Keplr wallet and show the connected address

## Screenshots

<img width="556" alt="image" src="https://github.com/graz-sh/graz/assets/49041460/2ab29f60-49b3-4da8-94ff-073877699e2f">

## Device

> Please complete the following device information.

**Desktop**

- OS: iOS
- Browser: Chrome
- Version: latest

**Comment by btc8436954** [comment]
cc @grikomsn

**Comment by codingki** [comment]
@bullishgopher I think you haven't pass RockChain ChainInfo in graz provider https://graz.sh/docs/getting-started#2-configure-grazoptions
