### ISSUE TITLE
useSigningClient is created using the wrong offlineSigner, meaning ledger's do not work

### ISSUE THREAD

**Issue by Callum-A** [strangelove-ventures/wadesta#21]
It currently uses the signer from `keplr.getOfflineSigner(chainId)` when it should use `keplr.getOfflineSignerAuto(chainId)`, maybe this should be specified by a flag as I am unsure if it breaks other bindings?

**Comment by codingki** [comment]
@Callum-A fixed on v0.0.12 Thanks for the report
