### ISSUE TITLE
Verify ledger support

### ISSUE THREAD

**Issue by grikomsn** [strangelove-ventures/wadesta#24]

**Comment by grikomsn** [comment]
https://github.com/cosmos/cosmjs/blob/main/packages/amino/src/signer.ts

**Comment by codingki** [comment]
This is related to #21, @Callum-A Can you test again in v.0.0.14 ?

**Comment by codingki** [comment]
native ledger wallet support is not yet added, but if we use supported wallet (keplr, leap, etc) and connect ledger to it. it should be supported.
