### ISSUE TITLE
Non signing cosmwasm client hook

### ISSUE THREAD

**Issue by Callum-A** [strangelove-ventures/wadesta#4]
Would be nice to also include a non signing cosmwasm client (CosmwasmClient) that can be used without connecting a wallet e.g. to purely load data before connecting. This allows dApps to have a read only view prior to wallet connection.

**Comment by codingki** [comment]
good suggestion, and we need to rename `client` -> `signingClient` and then add `CosmwasmClient` as `client`

**Comment by grikomsn** [comment]
@Callum-A would those clients be in sync with the connected account or separate with different configurations?

**Comment by Callum-A** [comment]
> @Callum-A would those clients be in sync with the connected account or separate with different configurations?

I was thinking you can spin it up doing `const client = useCosmWasmClient(chain.rpc)` where chain is a `GrazChain` although a user could just pass the RPC string

**Comment by grikomsn** [comment]
Updated store types[^1], created client related actions[^2] and hooks[^3]. Let me know what you think, @Callum-A!

[^1]: https://github.com/strangelove-ventures/graz/blob/ebec1c40d07f965039474048129c18cae469ad33/packages/graz/src/store/index.ts#L14-L18
[^2]: https://github.com/strangelove-ventures/graz/blob/dev/packages/graz/src/actions/clients.ts
[^3]: https://github.com/strangelove-ventures/graz/blob/dev/packages/graz/src/hooks/clients.ts

**Comment by Callum-A** [comment]
Had a usage of these this morning. I like this new setup. One small bit of feedback is that using SigningClient with custom details requires a signer to be passed and causes issues when linting with typescript due to offlineSigner returning null or OfflineSigner. (This could just be me being a typescript noob however)

**Comment by codingki** [comment]
> 

I like this approach

**Comment by codingki** [comment]
> Updated store types[1](#user-content-fn-1-117b04759b60bc9bbde1af6cbeffa900), created client related actions[2](#user-content-fn-2-117b04759b60bc9bbde1af6cbeffa900) and hooks[3](#user-content-fn-3-117b04759b60bc9bbde1af6cbeffa900). Let me know what you think, @Callum-A!
> 
> ## Footnotes
> 1. https://github.com/strangelove-ventures/graz/blob/ebec1c40d07f965039474048129c18cae469ad33/packages/graz/src/store/index.ts#L14-L18
>     [↩](#user-content-fnref-1-117b04759b60bc9bbde1af6cbeffa900)
> 2. https://github.com/strangelove-ventures/graz/blob/dev/packages/graz/src/actions/clients.ts [↩](#user-content-fnref-2-117b04759b60bc9bbde1af6cbeffa900)
> 3. https://github.com/strangelove-ventures/graz/blob/dev/packages/graz/src/hooks/clients.ts [↩](#user-content-fnref-3-117b04759b60bc9bbde1af6cbeffa900)

I like this approach

**Comment by grikomsn** [comment]
> Had a usage of these this morning. I like this new setup. One small bit of feedback is that using SigningClient with custom details requires a signer to be passed and causes issues when linting with typescript due to offlineSigner returning null or OfflineSigner. (This could just be me being a typescript noob however)

Several hooks/functions return either null to ensure that the data is actually there, so you need to check the nullish value beforehand. Could you provide an example or repro?

**Comment by Callum-A** [comment]
> > Had a usage of these this morning. I like this new setup. One small bit of feedback is that using SigningClient with custom details requires a signer to be passed and causes issues when linting with typescript due to offlineSigner returning null or OfflineSigner. (This could just be me being a typescript noob however)
> 
> Several hooks/functions return either null to ensure that the data is actually there, so you need to check the nullish value beforehand. Could you provide an example or repro?

My current solution:
```js
const { signer } = useSigners();
const { data: client } = useSigningClient({
    rpc: chain.rpc,
    // @ts-ignore
    offlineSigner: signer,
    signerOptions: {
        gasPrice: GasPrice.fromString(
            `${config.GAS_PRICE}${config.COIN_MINIMAL_DENOM}`
        )
    }
});
```

**Comment by grikomsn** [comment]
```ts
const { signer } = useSigners();
const { data: client } = useSigningClient({
    rpc: chain.rpc,
    // @ts-ignore
    offlineSigner: signer,
    signerOptions: {
        gasPrice: GasPrice.fromString(
            `${config.GAS_PRICE}${config.COIN_MINIMAL_DENOM}`
        )
    }
});
```

Based on this, reasone why `signer` is null because we do not know whether `signer` itself has been initialized before. Two suggestions: either force acknowleding it is not null (`signer!`) or check before accessing it (`if (signer)`).

**Comment by Callum-A** [comment]
> 

Perfect thank you! I'm going to carry on hacking away with Graz today, any other issues I'll open up
