### ISSUE TITLE
Cannot connect with Keplr Wallet extension with error "There is no chain info for uni-5"

### ISSUE THREAD

**Issue by NarutoUjumaki** [strangelove-ventures/wadesta#62]
I followed the [tutorial setup](https://strange.love/blog/how-to-connect-your-frontend-to-cosmos-blockchain) using cosmos-frontend and graz, but on clicking "connect wallet" it gives the said error.
I wish to connect with the cosmos public testnet (theta) instead.

![image](https://user-images.githubusercontent.com/124332015/221866919-3a515bec-94bb-4ae1-8e15-b77e32a7c4ef.png)

**Comment by codingki** [comment]
Hey @NarutoUjumaki what were you doing before this happen? are you switching to Juno testnet?

**Comment by NarutoUjumaki** [comment]
I am trying to connect to the CosmosHub testnet Theta.

**Comment by codingki** [comment]
Try to clear your browser `localhost` site data storage
