### ISSUE TITLE
Error while building project with graz

### ISSUE THREAD

**Issue by Xyzjesus** [strangelove-ventures/wadesta#66]
## Describe the bug
when i use graz cli -g to generate list of chains there's an error in compiler about 8-ball chain
![telegram-cloud-photo-size-2-5280528846254360298-y](https://user-images.githubusercontent.com/62913761/229426186-3f5ef93c-086a-4dc3-8e12-b7411906b117.jpg)
<img width="824" alt="Screenshot 2023-04-03 at 10 16 02" src="https://user-images.githubusercontent.com/62913761/229426314-4a5781ee-9cc7-4141-a77d-200450a064a4.png">
![telegram-cloud-photo-size-2-5285249169931485926-y](https://user-images.githubusercontent.com/62913761/229429536-997ea8d8-9696-4535-b014-47b9d8442acb.jpg)

when I change 8ball to eightball on localhost, I guess everything works
...

## Expected behavior

> A clear and concise description of what you expected to happen.

...

## Screenshots

> If applicable, add screenshots to help explain your problem.

...

## Device

> Please complete the following device information.

**Desktop**

- OS: MacOS
- Browser: Brave

**Smartphone**

## Additional context

> Add any other context about the problem here.

...

**Comment by codingki** [comment]
Hey @Xyzjesus thanks for the report, nice find!

**Comment by Xyzjesus** [comment]
hey @codingki thanks a lot bro. is't okay if I ask you to fix it asap? it looks like our builder isn't joking :D
<img width="1045" alt="Screenshot 2023-04-05 at 15 08 35" src="https://user-images.githubusercontent.com/62913761/230063855-e82537c7-fae2-4845-b56f-b35973ac29ab.png">

**Comment by Xyzjesus** [comment]
hey @codingki 
also we have problems with importing modules with graz/dist
do you know how to resolve it? 
<img width="630" alt="Screenshot 2023-04-07 at 14 49 52" src="https://user-images.githubusercontent.com/62913761/230596511-f6fdfff9-95d2-48c1-b12a-9e05e3384311.png">

**Comment by codingki** [comment]
Hey @Xyzjesus sorry to keep you waiting, will be fixed in the next release
