### ISSUE TITLE
Error with node_modules inside graz

### ISSUE THREAD

**Issue by Xyzjesus** [strangelove-ventures/wadesta#67]
## Describe the bug
hey, I have an issue: when I use imports from graz/dist is doesn't work. I've checked every lib but I think the problem is here. Also when I'm trying to build project on production (you can see https://gutenberg.tools/) the variable isConnected doesn't work on prod but works on localhost (you can try to clone the repo https://github.com/diekuche/gutenberg and run it). I guess the problem is in node modules that I can't import in components via graz. 

 
window.keplr is not initialised
...

## To Reproduce

1. Go to 'https://gutenberg.tools/'
2. Click on 'connect wallet'
3. See error

## Expected behavior

> A clear and concise description of what you expected to happen.

...

## Screenshots
<img width="432" alt="Screenshot 2023-04-07 at 17 17 29" src="https://user-images.githubusercontent.com/62913761/230615515-ac98a5ba-3e42-413a-8201-40586c9c2546.png">

> If applicable, add screenshots to help explain your problem.
<img width="643" alt="Screenshot 2023-04-07 at 17 18 12" src="https://user-images.githubusercontent.com/62913761/230615626-88264e26-66e9-4fd5-be27-8ad043e34921.png">

...

## Device

> Please complete the following device information.

**Desktop**

**Smartphone**

## Additional context

> Add any other context about the problem here.

...

**Comment by codingki** [comment]
We are going to deprecate ibc domains api in graz and might be publish a different package for that. Hope it fixes your issue

**Comment by codingki** [comment]
Hey @Xyzjesus try to update graz to the latest version `0.0.35` https://github.com/strangelove-ventures/graz/releases/tag/v0.0.35
