### ISSUE TITLE
Gas price must be set in the client options when auto gas is used

### ISSUE THREAD

**Issue by Callum-A** [strangelove-ventures/wadesta#7]
When using "auto" gas with the cosmwasm client it errors saying the gas prices must be set in the client config if using auto.
Error: Gas price must be set in the client options when auto gas is used.

Steps to reproduce:

1. Get a client using the client hook.
2. Attempt to execute a contract using the "auto" fee options
```js
try {
  await client?.execute(
    account.bech32Address || '',
    config.CONTRACT_ADDRESS,
    { delete_template: { id } },
    'auto'
  );
} catch (err) {
  console.log(err);
}
```

**Comment by codingki** [comment]
We rawly return `SigningCosmWasmClient`.
From `@cosmjs/cosmwasm-stargate` https://github.com/cosmos/cosmjs/blob/372f942d7cafbc1e769b206a733b61481180b57d/packages/cosmwasm-stargate/src/signingcosmwasmclient.ts#L518-L519 that error only occurred if there's no `this.gasPrice`. 
Have you tried outside `graz` @Callum-A ?

**Comment by Callum-A** [comment]
> https://github.com/cosmos/cosmjs/blob/372f942d7cafbc1e769b206a733b61481180b57d/packages/cosmwasm-stargate/src/signingcosmwasmclient.ts#L518-L519

Yes, I've setup a client before, however I think it would be beneficial to add gasConfiguration to the `GrazChain` type which then allows auto gas to be used out of the box. For example the `GrazChain` type could be extended to feature `gasPrice: string | undefined` and `gasDenom: string | undefined` if both of these are set the client can then be loaded with gasprices using `GasPrice.fromString("0.025ujunox")` e.g. for Juno Testnet

**Comment by Callum-A** [comment]
I should add, that adding this as an additional config would allow it to be used with cosmwasm contracts out of the box

**Comment by codingki** [comment]
CMIIW I think we need to pass `options: SigningCosmWasmClientOptions` with the `gasPrice` filled on this line to make `"auto"` work https://github.com/strangelove-ventures/graz/blob/dev/packages/graz/src/actions/account.ts#L28

**Comment by codingki** [comment]
Currently `GrazChain` purposes is only for `useConnect` and `useBalance`. `GrazChain` is simplified from keplr's `ChainInfo`. Good suggestion @Callum-A , What do you think @grikomsn?

**Comment by Callum-A** [comment]
> Currently `GrazChain` purposes is only for `useConnect` and `useBalance`. `GrazChain` is simplified from keplr's `ChainInfo`. Good suggestion @Callum-A , What do you think @grikomsn?

I have a current fix on my fork, I can open up the PR and we can talk through my approach?

**Comment by codingki** [comment]
@Callum-A sure
