### ISSUE TITLE
useCheckWallet returns true even if keplr not installed

### ISSUE THREAD

**Issue by greedyboi** [strangelove-ventures/wadesta#90]
## Describe the bug

When you have leap wallet extension installed but not keplr, `useCheckWallet(WalletType.KEPLR)` return true and `getWallet(WalletType.KEPLR)` works (and should not) using Leap so it opens Leap modal

## To Reproduce

1. Install Leap extension only
2. Select Keplr extension within any app (it should not be available as the extension is not installed)
3. It opens Leap modal

## Expected behavior

> A clear and concise description of what you expected to happen.

`useCheckWallet(WalletType.KEPLR)` should return false and `getWallet(WalletType.KEPLR)` should throw an error.

## Device

> Please complete the following device information.

**Desktop**

- OS: MacOS Ventura
- Browser Brave
- Version 1.52

**Comment by codingki** [comment]
@greedyboi Nice find! I successfully reproduced this issue in my end. This is not `graz` issue. I'm assuming leap extension injecting and replace `window.keplr` to `window.leap` when there's no keplr extension installed.

**Comment by codingki** [comment]
I already ask leap team waiting for their reply. I'll keep this issue open for a while

**Comment by codingki** [comment]
Currently it's expected 
![CleanShot 2023-06-06 at 00 32 00](https://github.com/strangelove-ventures/graz/assets/39829726/226fd6d9-d4f3-4429-8f8c-e646200a45e3)

**Comment by greedyboi** [comment]
@codingki  okay fair enough, I'll be monitoring changes from leap wallet then, thanks !
